#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    leftLine,       sensorReflection)
#pragma config(Sensor, in2,    middleLine,     sensorReflection)
#pragma config(Sensor, in3,    rightLine,      sensorReflection)
#pragma config(Sensor, in4,    armPot,         sensorPotentiometer)
#pragma config(Sensor, dgtl11, skyriseLeft,    sensorDigitalOut)
#pragma config(Sensor, dgtl12, skyriseRIght,   sensorDigitalOut)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port2,           driveLeft,     tmotorVex393_MC29, openLoop, encoderPort, I2C_2)
#pragma config(Motor,  port3,           driveRight,    tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port4,           liftLeft1,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           liftLeft2,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           liftRight1,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           liftRight2,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           intake,        tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!
#include "controller.c"
#include "autonomous.c"

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////
int autonSelection = 0;

void screen1() {
	clearLCDLine(0);
	clearLCDLine(1);

	displayLCDCenteredString(0,"Want the D?");
	displayLCDPos(1,1);
	displayNextLCDString("Red");
	displayLCDPos(1,12);
	displayNextLCDString("Blue");
}

void screen2() {
	clearLCDLine(0);
	clearLCDLine(1);

	displayLCDCenteredString(0,"ofc you do");
	displayLCDPos(1,0);
	displayNextLCDString("Skyrise");
	displayLCDPos(1,11);
	displayNextLCDString("Other");
}

void printOnly(string printString) {
	clearLCDLine(0);
	clearLCDLine(1);

	displayLCDCenteredString(0,printString);
}

void blink(int count) {
	for(int x = 0; x < count; x++) {
		bLCDBacklight = !bLCDBacklight;
		wait1Msec(100);
	}
}

void  homeMenu() {
	bLCDBacklight = true;
	screen1();

	do {
		if(nLCDButtons==1) {
			screen2();
			while(nLCDButtons==1) {} //Wait until button released
			wait1Msec(500);

			do {
				if(nLCDButtons==1) {
					string x = "Red - Skyrise";
					printOnly(x);
					blink(3);
					bLCDBacklight = true;
					autonSelection = 1;

					} else if(nLCDButtons==4) {
					string x = "Red - Other";
					printOnly(x);
					blink(3);
					bLCDBacklight = true;
					autonSelection = 2;

				} else if(nLCDButtons==2) {
					homeMenu();
				}
			} while(bLCDBacklight==0);

			}else if(nLCDButtons==4) {
			screen2();
			while(nLCDButtons==1) {} //Wait until button released
			wait1Msec(500);driveRight

			do {
				if(nLCDButtons==1) {
					string x = "Blue - Skyrise";
					printOnly(x);
					blink(3);
					bLCDBacklight = true;
					autonSelection = 3;

					} else if(nLCDButtons==4) {
					string x = "Blue - Other";
					printOnly(x);
					blink(3);
					bLCDBacklight = true;
					autonSelection = 4;

				} else if(nLCDButtons==2) {
					homeMenu();
				}
			} while(bLCDBacklight==0);
		}
	} while (bLCDBacklight==0);
}

void pre_auton()
{
	//homeMenu();
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////w////////////////////////////////////////////////////////////

task autonomous() {
	blueAuton();
	//if(autonSelection==0){

	//}else if(autonSelection==1) {
	//	redAuton();
	//}else if(autonSelection==2) {
	//	otherAuton();
	//}else if(autonSelection==3) {
	//	blueAuton();
	//}else if(autonSelection==4) {
	//	otherAuton();
	//}else {

	//}
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	bLCDBacklight = false;
	clearLCDLine(0);
	clearLCDLine(1);

	displayLCDCenteredString(0,"lih");
	controller();
}
