#pragma config(Motor,  port1,           driveLeft1,    tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           driveLeft2,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           driveRight1,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           driveRight2,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           liftLeft1,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           liftLeft2,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           liftRight1,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           liftRight2,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           intake,        tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!
#include "controller.c"
#include "autonomous.c"

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;
	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
  ourAutonomous();
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	controller();
}
